hw_django_skypro/config/catalog/urls.py
from django.urls import path
from catalog.views import home, contact_view, product_detail
from catalog.apps import CatalogConfig


app_name = CatalogConfig.name

urlpatterns = [
    path("", home),
    path("contact/", contact_view),
    path('product/<int:product_id>/', product_detail, name='product_detail'),
]

hw_django_skypro/config/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('catalog.urls', namespace='catalog')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

hw_django_skypro/config/catalog/models.py
from django.db import models

# Create your models here.

hw_django_skypro/config/catalog/views.py
from django.shortcuts import render
from django.http import HttpResponse

import json
import os


def home(request):
    # Построение пути к файлу products.json относительно базовой директории проекта
    # file_path = os.path.join(settings.BASE_DIR, 'catalog/data/products.json')

    # Чтение информации о продуктах из JSON-файла
    with open('catalog/data/products.json') as json_file:
        products_data = json.load(json_file)

    context = {
        'products': products_data,
    }

    return render(request, 'catalog/home.html', context)


def contact_view(request):
    return render(request, "catalog/contact.html")


def product_detail(request, product_id):
    with open('catalog/data/products.json') as json_file:
        products_data = json.load(json_file)
        for product_data in products_data:
            if product_data['id'] == product_id:
                break
    context = {
        'product': product_data,
    }
    return render(request, 'catalog/product_detail.html', context)

hw_django_skypro/config/catalog/templates/catalog/contact.html
{% extends 'layout.html' %}

{% block title %}Contact - Electronic Store{% endblock %}

{% block content %}
    <h1>Contact Us</h1>

    <p>Feel free to reach out to us for any inquiries or assistance.</p>

    <div class="row">
        <div class="col-md-6">
            <h2>Our Information</h2>
            <p>
                <strong>Electronic Store</strong><br>
                123 Tech Street<br>
                Cityville, TX 12345<br>
                Email: info@electronicstore.com<br>
                Phone: (123) 456-7890
            </p>
        </div>
        <div class="col-md-6">
            <h2>Contact Form</h2>
            <form>
                <div class="form-group">
                    <label for="name">Your Name</label>
                    <input type="text" class="form-control" id="name" placeholder="Enter your name">
                </div>
                <div class="form-group">
                    <label for="email">Your Email</label>
                    <input type="email" class="form-control" id="email" placeholder="Enter your email">
                </div>
                <div class="form-group">
                    <label for="message">Message</label>
                    <textarea class="form-control" id="message" rows="4" placeholder="Type your message"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}

hw_django_skypro/config/catalog/templates/catalog/home.html
{% extends 'layout.html' %}
{% load custom_filters %}


{% block title %}Home - Electronic Store{% endblock %}

{% block content %}

<style>
    .product-image {
        height: 200px; /* Установите желаемую фиксированную высоту */
        object-fit: cover; /* Сохраняет пропорции изображения и заполняет всю доступную область */
        width: 100%; /* Гарантирует, что изображение займет всю ширину контейнера */
    }
</style>
    <h1>Welcome to our Electronic Store!</h1>

    <div class="row">
        {% for product in products %}
            <div class="col-md-4 mb-4">
                <div class="card">
                    <img src="{% mediapath product.image_url %}" class="card-img-top product-image" alt="{{ product.name }}"/>
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p class="card-text">{{ product.description|slice:":100" }}</p>
                        <p class="card-text">Price: ${{ product.price }}</p>
                        <a href="{% url 'catalog:product_detail' product_id=product.id %}">View Details</a>

                        <a href="#" class="btn btn-primary">Add to Cart</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

hw_django_skypro/config/catalog/templates/catalog/layout.html
{% load custom_filters %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Electronic Store{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Electronic Store</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/contact">Contact</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>

</html>

hw_django_skypro/config/catalog/templates/catalog/product_detail.html
{% extends 'layout.html' %}
{% load custom_filters %}

{% block title %}{{ product.name }} - Electronic Store{% endblock %}

{% block content %}
    <div class="container mt-4">
        <div class="row">
            <div class="col-md-6">
                <img src="{% mediapath product.image_url %}" class="img-fluid" alt="{{ product.name }}">
            </div>
            <div class="col-md-6">
                <h1>{{ product.name }}</h1>
                <p class="lead">{{ product.description }}</p>
                <p>Price: ${{ product.price }}</p>
                <!-- Другая информация о товаре, которую вы хотите отобразить -->
            </div>
        </div>
    </div>
{% endblock %}
 